import type { Metadata } from "next";
import Header from "@/components/Header";
import { getMessagesList } from "@/actions/messages";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessagesList()
  return (
    <div>
        <Header messagesCount={messages ? messages.length : 0}  />
        <main>
          {children}
        </main>
    </div>
  );
}
